### ISSUE TITLE
Нарисовать кастомные иконки для маркеров.

### ISSUE THREAD

**Issue by stepan-anokhin** [stepan-anokhin/spb-histmap#10]
## Контекст

Как пользователь, я хочу легко определять тип события по его внешнему виду. 

## Задача

Нарисовать маркеры для каждого типа события. Иконки должны быть интуитивно понятными и достаточно различным, чтобы отличать их с первого взгляда.

**Comment by gellouglas** [comment]
Нужны размеры и формат иконок.

**Comment by gellouglas** [comment]
Иконку для самолета можно выдернуть тут
https://img2.freepng.ru/20180407/fte/kisspng-airplane-bomber-fighter-aircraft-clip-art-jet-5ac85a4673c309.8434278015230797504742.jpg

**Comment by stepan-anokhin** [comment]
Короче, закрываю эту задачу, потому что художники заартачились, а иконки мы уже взяли бесплатные.
