### ISSUE TITLE
Интегрировать кастомные иконки маркеров.

### ISSUE THREAD

**Issue by stepan-anokhin** [stepan-anokhin/spb-histmap#11]
Зависит от #10 

## Контекст

Как пользователь, я хочу легко определять тип события по его внешнему виду. 

## Задача

Интегрировать кастомные иконки в приложение. 

## Ресурсы

* [custom marker icon with react-leaflet](https://stackoverflow.com/questions/47723812/custom-marker-icon-with-react-leaflet) - вопрос на StackOverflow
* [Markers With Custom Icons](https://leafletjs.com/examples/custom-icons/) - туториал по добавлению кастомных иконок маркеров в `leaflet.js`

Если не срастётся с привлечением художников, можно использовать вот эти бесплатные иконки:
1. [Bomb](https://www.flaticon.com/premium-icon/bomb_3464631)
2. [Fire](https://www.flaticon.com/free-icon/fire_785116)
3. [Bomb Vertical](https://www.flaticon.com/premium-icon/bomb_4181750)

**Comment by gellouglas** [comment]
На первоначальном этапе предлагаю условно разделить стандартные маркеры на две группы, просто перекрасив их :

- синие - для отображения попадания авиабомб
- красные - для попадания артснарядов.
